//! Data rebalancing for cluster membership changes.
//!
//! When a node is added or removed from the cluster, the consistent hash ring
//! remaps some key ranges to different nodes. The [`Rebalancer`] computes a
//! [`RebalancePlan`] describing which documents must move, and provides an
//! async [`execute`](Rebalancer::execute) method to stream them safely.
//!
//! # Safety Guarantees
//!
//! - Documents are **copied** to the destination before being deleted from the
//!   source. If a transfer fails mid-way, the source retains the document.
//! - Ring membership is updated **only after all moves complete** so that
//!   reads during rebalancing still hit the old node.
//! - Each [`DataMove`] is independent and can be retried without side effects.

use serde::{Deserialize, Serialize};
use std::fmt;

use crate::cluster::NodeId;
use crate::document::DocumentId;

// ---------------------------------------------------------------------------
// DataMove
// ---------------------------------------------------------------------------

/// A single document migration between two nodes.
///
/// Represents the intent to copy a document from `from_node` to `to_node`.
/// The source is not deleted until the destination confirms receipt.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct DataMove {
    /// The document to migrate.
    pub document_id: DocumentId,
    /// The node currently holding the document.
    pub from_node: NodeId,
    /// The node that should receive the document.
    pub to_node: NodeId,
}

impl fmt::Display for DataMove {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            f,
            "{}: {} → {}",
            self.document_id, self.from_node, self.to_node
        )
    }
}

// ---------------------------------------------------------------------------
// RebalancePlan
// ---------------------------------------------------------------------------

/// A plan describing all document moves needed for a cluster topology change.
///
/// Generated by [`ClusterRouter::rebalance_plan`](crate::cluster_router::ClusterRouter::rebalance_plan)
/// and executed by [`Rebalancer::execute`].
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct RebalancePlan {
    /// The ordered list of document moves.
    pub moves: Vec<DataMove>,
}

impl RebalancePlan {
    /// Create an empty rebalance plan (no moves needed).
    pub fn empty() -> Self {
        Self { moves: Vec::new() }
    }

    /// Return the number of document moves in this plan.
    pub fn move_count(&self) -> usize {
        self.moves.len()
    }

    /// Return `true` if no documents need to move.
    pub fn is_empty(&self) -> bool {
        self.moves.is_empty()
    }

    /// Return unique source nodes involved in this plan.
    pub fn source_nodes(&self) -> Vec<NodeId> {
        let mut sources: Vec<NodeId> = self.moves.iter().map(|m| m.from_node).collect();
        sources.sort_by_key(|id| id.as_u64());
        sources.dedup();
        sources
    }

    /// Return unique destination nodes involved in this plan.
    pub fn destination_nodes(&self) -> Vec<NodeId> {
        let mut dests: Vec<NodeId> = self.moves.iter().map(|m| m.to_node).collect();
        dests.sort_by_key(|id| id.as_u64());
        dests.dedup();
        dests
    }
}

impl fmt::Display for RebalancePlan {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            f,
            "RebalancePlan({} moves, {} sources, {} destinations)",
            self.move_count(),
            self.source_nodes().len(),
            self.destination_nodes().len()
        )
    }
}

// ---------------------------------------------------------------------------
// RebalanceStatus
// ---------------------------------------------------------------------------

/// Status of a rebalance operation.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[non_exhaustive]
pub enum RebalanceStatus {
    /// Rebalance has not started.
    Pending,
    /// Rebalance is in progress.
    InProgress,
    /// All moves completed successfully.
    Completed,
    /// Rebalance failed; source data is intact.
    Failed,
}

impl fmt::Display for RebalanceStatus {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            RebalanceStatus::Pending => write!(f, "Pending"),
            RebalanceStatus::InProgress => write!(f, "InProgress"),
            RebalanceStatus::Completed => write!(f, "Completed"),
            RebalanceStatus::Failed => write!(f, "Failed"),
        }
    }
}

// ---------------------------------------------------------------------------
// Rebalancer
// ---------------------------------------------------------------------------

/// Executes a [`RebalancePlan`] by streaming documents between nodes.
///
/// The rebalancer is stateless — it takes a plan and a connection pool,
/// streams each document from source to destination, confirms receipt,
/// and only then deletes the source copy.
///
/// In the current core crate this is a logical placeholder; the actual
/// gRPC streaming is implemented in the `network` crate. The core crate
/// provides the plan computation and the data types.
pub struct Rebalancer;

impl Rebalancer {
    /// Execute a rebalance plan.
    ///
    /// For each [`DataMove`] in the plan:
    /// 1. Read the document from `from_node` via gRPC streaming.
    /// 2. Write the document to `to_node`.
    /// 3. Wait for `to_node` to acknowledge the write.
    /// 4. Delete the document from `from_node`.
    ///
    /// If any step fails, the move is skipped (source retains the document)
    /// and the failure is logged. The ring membership is updated only after
    /// **all** moves succeed.
    ///
    /// # Note
    ///
    /// This method accepts the plan by value and returns the execution status.
    /// The actual network transport is handled by the `network` crate; this
    /// method provides the orchestration logic and will be wired up when the
    /// gRPC connection pool is available.
    pub async fn execute(plan: RebalancePlan) -> RebalanceStatus {
        if plan.is_empty() {
            return RebalanceStatus::Completed;
        }

        tracing::info!(
            moves = plan.move_count(),
            sources = plan.source_nodes().len(),
            destinations = plan.destination_nodes().len(),
            "Starting rebalance"
        );

        // In the core crate, we perform a dry-run: log each move.
        // The network crate will override this with real gRPC streaming.
        for data_move in &plan.moves {
            tracing::info!(
                doc = %data_move.document_id,
                from = %data_move.from_node,
                to = %data_move.to_node,
                "Rebalance move (dry run)"
            );
        }

        tracing::info!("Rebalance completed (dry run)");
        RebalanceStatus::Completed
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn empty_plan() {
        let plan = RebalancePlan::empty();
        assert!(plan.is_empty());
        assert_eq!(plan.move_count(), 0);
        assert!(plan.source_nodes().is_empty());
        assert!(plan.destination_nodes().is_empty());
    }

    #[test]
    fn plan_with_moves() {
        let plan = RebalancePlan {
            moves: vec![
                DataMove {
                    document_id: DocumentId::new("doc-1"),
                    from_node: NodeId::new(1),
                    to_node: NodeId::new(4),
                },
                DataMove {
                    document_id: DocumentId::new("doc-2"),
                    from_node: NodeId::new(2),
                    to_node: NodeId::new(4),
                },
                DataMove {
                    document_id: DocumentId::new("doc-3"),
                    from_node: NodeId::new(1),
                    to_node: NodeId::new(4),
                },
            ],
        };

        assert_eq!(plan.move_count(), 3);
        assert!(!plan.is_empty());

        let sources = plan.source_nodes();
        assert_eq!(sources.len(), 2); // node-1 and node-2

        let dests = plan.destination_nodes();
        assert_eq!(dests.len(), 1); // node-4
        assert_eq!(dests[0], NodeId::new(4));
    }

    #[test]
    fn data_move_display() {
        let m = DataMove {
            document_id: DocumentId::new("doc-42"),
            from_node: NodeId::new(1),
            to_node: NodeId::new(4),
        };
        let display = format!("{m}");
        assert!(display.contains("doc-42"));
        assert!(display.contains("node-1"));
        assert!(display.contains("node-4"));
    }

    #[test]
    fn rebalance_plan_display() {
        let plan = RebalancePlan {
            moves: vec![DataMove {
                document_id: DocumentId::new("doc-1"),
                from_node: NodeId::new(1),
                to_node: NodeId::new(2),
            }],
        };
        let display = format!("{plan}");
        assert!(display.contains("1 moves"));
    }

    #[test]
    fn rebalance_plan_serde_roundtrip() {
        let plan = RebalancePlan {
            moves: vec![DataMove {
                document_id: DocumentId::new("doc-1"),
                from_node: NodeId::new(1),
                to_node: NodeId::new(4),
            }],
        };

        let json = serde_json::to_string(&plan).unwrap();
        let back: RebalancePlan = serde_json::from_str(&json).unwrap();
        assert_eq!(plan, back);
    }

    #[test]
    fn rebalance_status_display() {
        assert_eq!(format!("{}", RebalanceStatus::Pending), "Pending");
        assert_eq!(format!("{}", RebalanceStatus::InProgress), "InProgress");
        assert_eq!(format!("{}", RebalanceStatus::Completed), "Completed");
        assert_eq!(format!("{}", RebalanceStatus::Failed), "Failed");
    }

    #[tokio::test]
    async fn execute_empty_plan_completes() {
        let status = Rebalancer::execute(RebalancePlan::empty()).await;
        assert_eq!(status, RebalanceStatus::Completed);
    }

    #[tokio::test]
    async fn execute_plan_dry_run_completes() {
        let plan = RebalancePlan {
            moves: vec![DataMove {
                document_id: DocumentId::new("doc-1"),
                from_node: NodeId::new(1),
                to_node: NodeId::new(4),
            }],
        };
        let status = Rebalancer::execute(plan).await;
        assert_eq!(status, RebalanceStatus::Completed);
    }
}
